-- RecoverIQ initial schema migration (PostgreSQL/Supabase compatible).
-- SQLAlchemy metadata is authoritative; this migration documents/deploys the core tables.
CREATE TABLE IF NOT EXISTS users (id varchar(36) PRIMARY KEY, email varchar(255) UNIQUE NOT NULL, name varchar(120) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS merchants (id varchar(36) PRIMARY KEY, user_id varchar(36) REFERENCES users(id), name varchar(160) NOT NULL, currency varchar(3) NOT NULL, demo_mode boolean NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS customers (id varchar(36) PRIMARY KEY, merchant_id varchar(36) REFERENCES merchants(id), name varchar(120) NOT NULL, email varchar(255) NOT NULL, phone varchar(30) NOT NULL, value_segment varchar(20) NOT NULL, age_days integer NOT NULL, previous_success_count integer NOT NULL, previous_failure_count integer NOT NULL, previous_recovery_count integer NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id varchar(36) PRIMARY KEY, merchant_id varchar(36) REFERENCES merchants(id), customer_id varchar(36) REFERENCES customers(id), external_id varchar(100) UNIQUE, amount double precision NOT NULL CHECK(amount >= 0), currency varchar(3) NOT NULL, method varchar(30) NOT NULL, failure_reason varchar(50) NOT NULL, status varchar(30) NOT NULL, occurred_at timestamptz NOT NULL, recovered_at timestamptz);
CREATE TABLE IF NOT EXISTS recovery_cases (id varchar(36) PRIMARY KEY, merchant_id varchar(36) REFERENCES merchants(id), payment_id varchar(36) UNIQUE REFERENCES payments(id), state varchar(30) NOT NULL, priority varchar(20) NOT NULL, probability double precision NOT NULL CHECK(probability BETWEEN 0 AND 1), expected_value double precision NOT NULL, recommended_action varchar(50) NOT NULL, guardrail_decision varchar(30) NOT NULL, recovery_attempts integer NOT NULL, customer_contacts integer NOT NULL, payment_link_id varchar(100), payment_link_url varchar(500), last_contact_at timestamptz, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
-- Remaining normalized tables are created by SQLAlchemy metadata: payment_attempts,
-- recovery_actions, recovery_workflows, model_predictions, agent_decisions, audit_logs, webhook_events.
